language: generic
services:
  - docker

# we want our travis run on only master branch
branches:
  only:
    - master

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  # Tag
  - docker tag udagram-api-feed callmeket/udagram-api-feed:v1
  - docker tag udagram-api-user callmeket/udagram-api-user:v1
  - docker tag udagram-frontend callmeket/udagram-frontend:v1
  - docker tag reverseproxy callmeket/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push callmeket/udagram-api-feed:v1
  - docker push callmeket/udagram-api-user:v1
  - docker push callmeket/udagram-frontend:v1
  - docker push callmeket/reverseproxy:v1
  - echo "Completed!"

